### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by a1batross**
Tested on Steam Deck with build from Actions, works for me. Didn't notice any performance regress.

### CODE REVIEW

**Comment by a1batross** [comment]
Tested on Steam Deck, works for me. Didn't notice any performance regress

**Comment by KyleGospo** [comment]
~~With this build I am getting very inconsistent mouse button inputs, with the mouse either being unrecognized entirely or sticking on.~~

~~I also tried resetting controls to default just in case, same result.~~

Disregard, fixed by deleting the rt & rt_bin folders and replacing them with fresh ones, works excellent here.

**Comment by a1batross** [comment]
сс @sultim-t

**Comment by palaashatri** [comment]
I guess we need someone to check build on Windows too for @sultim-t to consider this MR? 
But I'm way too lazy to install Visual Studio (and the whole gigantic bugapoo it downloads during installation), so maybe if someone can help here and verify if it also installs and runs as expected on Windows too?

**Comment by a1batross** [comment]
I doubt he cares about this.

I'm closing this, to me it's better wait for [original RTX mod](https://github.com/w23/xash3d-fwgs) that isn't hardcoded to exact Half-Life maps and has proper Vulkan renderer, that potentially gonna get merged to upstream.

**Comment by sultim-t** [comment]
I care. Sadly, I just don't have time lately :(
Sorry

Clearly it's a lot of work to integrate the upstream changes! Thank you, I will merge it as soon as I will have time

**Comment by palaashatri** [comment]
@a1batross maybe you can open the MR again?

**Comment by a1batross** [comment]
@palaashatri I could but I don't want to waste my time on a fork that wasn't meant to be maintained. Last commit was March 4, a month ago. And meanwhile we already patched a few bugs in upstream.

There are too many cases like this, somebody forks your code, dirty hacks a feature into it, gets into news headlines and that's all, just death. Hell, even I did that, but in the end I understood that it's better to work with the community and not force community to workaround your hacks.

**Comment by palaashatri** [comment]
🙄

**Comment by a1batross** [comment]
🤷🏽

**Pull request closed without merging**
